language: node_js

node_js: lts/*

script:
  # - npm run lint
  - npm run build

stages:
  - name: release
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: release
      language: node_js
      node_js: 'lts/*'
      script: npx semantic-release
