language: node_js
node_js: lts/*

stages:
  - name: release
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: release
      script: npx semantic-release
